name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - main

    paths:
      - .github/workflows/profile-3d.yml

  # pull_request: need to set head_ref
  #   branches:
  #     - main

  schedule: # 00:00 IST == 05:30 UTC
    - cron: "*/15 * * * *"
    # 00:00 IST == 05:30 UTC
    - cron: "30 5 * * *"
  workflow_dispatch:

concurrency:
  group: git-commit
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      # - uses: yoshi389111/github-profile-3d-contrib@0.7.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     USERNAME: ${{ github.repository_owner }}

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTINGS_JSON: profile-3d-contrib/rainbow.json

      # - name: Commit & Push
      #   run: |
      #     git config user.name Baymax
      #     git config user.email laciferin@gmail.com
      #     git add -A .
      #     git commit -m "update: profile-3d"
      #     git push

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit
        with:
          commit_message: "update: profile-3d"
          commit_options: "--no-verify --signoff"
          add_options: "-u"
          # branch: "cron/date"
          create_branch: true
          push_options: --force

      - name: "Run if changes have been detected"
        if: steps.auto-commit.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit.outputs.changes_detected == 'false'
        run: echo "No Changes!"

      - uses: vimtor/action-zip@v1.1
        with:
          files: ${{github.workspace}}/profile-3d-contrib
          recursive: true
          dest: profile-3d-contrib.zip

      - uses: actions/upload-artifact@v3
        with:
          name: profile-3d-contrib.zip
          path: ${{ github.workspace }}/profile-3d-contrib.zip
