name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - main

    paths:
      - .github/workflows/profile-3d.yml

  # pull_request: need to set head_ref
  #   branches:
  #     - main

  schedule: # 00:00 IST == 05:30 UTC
    - cron: "*/15 * * * *"
    # 00:00 IST == 05:30 UTC
    - cron: "30 5 * * *"
  workflow_dispatch:

concurrency:
  group: git-commit
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      # - uses: yoshi389111/github-profile-3d-contrib@0.7.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     USERNAME: ${{ github.repository_owner }}

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTINGS_JSON: profile-3d-contrib/rainbow.json

      - name: Commit & Push
        run: |
          git config user.name Baymax
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
