name: Update Github Activity

on:
  # push: push not supported by this action
  #   branches:
  #     - main
  #   tags:

  # push:
  #   paths: #not supported by action
  #     - .github/workflows/update-github-activity.yml

  # pull_request:
  #   branches:
  #     - main

  schedule: 
    - cron: "*/5 * * * *"
    # 00:00 IST == 05:30 UTC
    - cron: "30 5 * * *"
  workflow_dispatch:

concurrency:
  group: git-commit
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ ci: Update README with the recent activity"
          COMMIT_NAME: Baymax
          COMMIT_EMAIL: "laciferin@gmail.com"
          TARGET_FILE: README.md
          MAX_LINES: 5
